books/urls.py
from django.urls import path

from . import views


app_name = "books"

urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('book/<int:pk>/', views.book_detail, name='book_detail'),
    path('authors/', views.author_list, name='author_list'),
    path('author/<int:pk>/', views.author_detail, name='author_detail'),
    path('my-borrows/', views.user_borrows, name='user_borrows'),
]

dingo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("login/", LoginView.as_view(), name="login"),
    # musi być by zadziałało przekierowanie po logout
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path('books/', include("books.urls")),
    path('maths/', include("maths.urls")),
    path('', include("greetings.urls")),
    path('sessions/', include("sessions.urls")),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maths/urls.py
from django.urls import path
from maths.views import Calculator, maths_list, math_details, results_list

app_name = "maths"
urlpatterns = [
    path('', Calculator.math),
    path('add/<a>/<b>', Calculator.add),
    path('sub/<a>/<b>', Calculator.sub),
    path('mul/<a>/<b>', Calculator.mul),
    path('div/<a>/<b>', Calculator.div),
    path('histories/', maths_list, name="list"),
    path('histories/<int:id>', math_details, name="details"),
    path('results/', results_list, name="results"),
]

posts/urls.py
from django.urls import path
from django.views.generic import ListView

from posts.models import Osoba
from .views import (
    post_list,
    post_detail,
    post_create,
    author_list,
    author_detail,
    author_create,
    PostUpdateView
)


app_name = 'posts'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('post/new/', post_create, name='post_create'),
    path('post/<int:pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    # path('post_list', ListView.as_view(model=Post), name="posts_list"),
    # posts/osoba_list.html  //  'wzrost__gte' filtr po wzroście osoby
    path('wery_tall/', ListView.as_view(queryset=Osoba.objects.filter(wzrost__gte=200))),
    path('authors/', author_list, name='author_list'),
    path('author/<int:pk>/', author_detail, name='author_detail'),
    path('author/new/', author_create, name='author_create'),
]

templates/main.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Dingo{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'maths/css/style.css' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
  
      <a class="navbar-brand" href="{% url 'welcome' %}">
        <div class="d-flex flex-column">
          <strong>DINGO</strong>
          <small class="text-muted" style="font-size: 0.9rem;">Working space with perspective...</small>
        </div>
      </a>
  
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav text-right">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:author_list' %}">Authors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:book_list' %}">Books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:user_borrows' %}">Borrowed Books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'maths:list' %}">Maths</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:post_list' %}">Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item d-flex align-items-center">
            <span class="nav-link p-0">{{ user.username }}</span>
            <span class="nav-item text-muted me-3">|</span>
            <form method="post" action="{% url 'logout' %}" class="m-0">
              {% csrf_token %}
              <button type="submit" class="btn btn-link p-0" style="border:none; background:none;">Logout</button>
            </form>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
          {% endif %}

        </ul>
      </div>
  
    </div>
  </nav>
  

<!-- Zamiast django_bootstrap_breadcrumbs <- Nie kompatybilne z Django 4+ -->
<nav class="bg-light py-2 px-3 mb-4" aria-label="breadcrumb">
    <div class="container">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{% url 'welcome' %}">Home</a></li>
            {% if request.resolver_match.url_name != "welcome" %}
                <li class="breadcrumb-item active" aria-current="page">
                    /{{ request.resolver_match.url_name }}
                </li>
            {% endif %}
        </ol>
    </div>
</nav>

<div class="container">
    {% bootstrap_messages %}

    {% block content %}
        <p>This is default content. Override this in templates.</p>
    {% endblock %}
</div>

</body>
</html>