books/urls.py
from django.urls import path

from . import views


app_name = "books"

urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('book/<int:pk>/', views.book_detail, name='book_detail'),
    path('authors/', views.author_list, name='author_list'),
    path('author/<int:pk>/', views.author_detail, name='author_detail'),
    path('my-borrows/', views.user_borrows, name='user_borrows'),
]

dingo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("login/", LoginView.as_view(), name="login"),
    # musi być by zadziałało przekierowanie po logout
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path('books/', include("books.urls")),
    path('maths/', include("maths.urls")),
    path('', include("greetings.urls")),
    path('sessions/', include("sessions.urls")),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from django.views.generic import ListView

from posts.models import Osoba
from .views import (
    post_list,
    post_detail,
    post_create,
    author_list,
    author_detail,
    author_create,
    PostUpdateView
)


app_name = 'posts'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('post/new/', post_create, name='post_create'),
    path('post/<int:pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    # path('post_list', ListView.as_view(model=Post), name="posts_list"),
    # posts/osoba_list.html  //  'wzrost__gte' filtr po wzroście osoby
    path('wery_tall/', ListView.as_view(queryset=Osoba.objects.filter(wzrost__gte=200))),
    path('authors/', author_list, name='author_list'),
    path('author/<int:pk>/', author_detail, name='author_detail'),
    path('author/new/', author_create, name='author_create'),
]

posts/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    nick = models.CharField(max_length=20, unique=True)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.nick


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to='photos/%Y/%m/%d', null=True, blank=True)
    tags = models.ManyToManyField("posts.Tag", related_name="posts")

    def __str__(self):
        return self.title


class Tag(models.Model):
    word = models.CharField(max_length=50, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.word


class Osoba(models.Model):
    imie = models.CharField(max_length=200)
    nazwisko = models.CharField(max_length=200)
    wzrost = models.IntegerField()

    def __str__(self):
        return f"{self.imie} {self.nazwisko}"

posts/forms.py
from django import forms

from .models import Post, Author


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "author", "image", "tags"]


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['nick', 'email']

posts/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator

from .models import Post, Author
from .forms import PostForm, AuthorForm


@method_decorator(login_required, name='dispatch')
@method_decorator(permission_required('posts.change_post', raise_exception=True), name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_form.html'
    success_url = '/posts/'


def post_list(request):
    posts = Post.objects.order_by('-created')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    posts_page = paginator.get_page(page_number)

    if request.method == "POST":
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:post_list')
    else:
        form = PostForm()

    return render(request, "posts/post_list.html", {
        "posts": posts_page,
        "form": form
    })


# def posts_list(request):
#     posts = Post.objects.all()
#     form = PostForm()
#     if request.method == "POST":
#         form = PostForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             messages.add_message(
#                 request,
#                 messages.SUCCESS,
#                 "Dodano nowy Post!!"
#             )


# """
# Tylko zalogowani użytkownicy będą mogli dodawać nowe posty.
# Usuniemy wtedy z naszego formularza pole author (poprzez odpowiednie ustawienie fields),
# ale model wymagać będzie nadal podania autora.
# Wtedy będziemy mogli wskazać, że to zalogowany użytkownik jest autorem w następujący sposób:
# """
# if form.is_valid():
#        post = form.save(commit=False)
#        post.author = request.user
#        post.save()


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'posts/post_detail.html', {'post': post})


def post_create(request):
    if request.method == "POST":
        # form = PostForm(request.POST)
        # form = ResultForm(data=request.POST, files=request.FILES)
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:post_list')
    else:
        form = PostForm()
    return render(request, 'posts/post_form.html', {'form': form})


def author_list(request):
    authors = Author.objects.all()
    return render(request, 'posts/author_list.html', {'authors': authors})


def author_detail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    return render(request, 'posts/author_detail.html', {'author': author})


def author_create(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:author_list')
    else:
        form = AuthorForm()
    return render(request, 'posts/author_form.html', {'form': form})

posts/templates/posts/author_detail.html
{% extends "main.html" %}

{% block title %}{{ author.nick }}{% endblock %}

{% block content %}
   <h2>{{ author.nick }}</h2>
   <p><strong>Email:</strong> {{ author.email }}</p>
   <h3>Posty autora:</h3>
   <ul>
       {% for post in author.post_set.all %}
           <li><a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a></li>
       {% endfor %}
   </ul>
   <a href="{% url 'posts:author_list' %}" class="btn btn-secondary">Powrót do listy autorów</a>
{% endblock %}

posts/templates/posts/author_form.html
{% extends "main.html" %}

{% block title %}Dodaj autora{% endblock %}

{% block content %}
   <h2>Dodaj nowego autora</h2>
   <form method="post">
       {% csrf_token %}
       {{ form.as_p }}
       <button type="submit">Zapisz</button>
       <a href="{% url 'posts:author_list' %}" class="btn btn-secondary">Powrót</a>
   </form>
{% endblock %}

posts/templates/posts/author_list.html
{% extends "main.html" %}

{% block title %}Lista autorów{% endblock %}

{% block content %}
   <h2>Lista autorów</h2>
   <ul>
       {% for author in authors %}
           <li><a href="{% url 'posts:author_detail' author.id %}">{{ author.nick }}</a> – {{ author.email }}</li>
       {% endfor %}
   </ul>
   <a href="{% url 'posts:author_create' %}" class="btn btn-secondary">Dodaj nowego autora</a>
   
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "main.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
   <h1>{{ post.title }}</h1>
   <h2>{{ post.author.nick }} | {{ post.created }}</h2>
   <p>{{ post.content }}</p>
   
   {% if post.image %}
      <div><img src="{{ post.image.url }}" class="img-fluid" style="max-width: 400px;"></div>
   {% else %}
      <p><em>Brak obrazka</em></p>
   {% endif %}

   {% if perms.posts.change_post %}
      <a href="{% url 'posts:post_edit' post.id %}" class="btn btn-warning">Edytuj</a>
   {% endif %}

   <a href="{% url 'posts:post_list' %}" class="btn btn-secondary">Powrót do listy</a>
{% endblock %}

posts/templates/posts/post_form.html
{% extends "main.html" %}

{% load bootstrap4 %}

{% block title %}{{ form.instance.pk|yesno:"Edytuj post / Dodaj post" }}{% endblock %}

{% block content %}
   <h2>{{ form.instance.pk|yesno:"Edytuj post / Dodaj nowy post" }}</h2>
   <form method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        {% bootstrap_form form  %}
        <button type="submit" class="btn btn-primary">Zapisz</button>
    </form>
   <a href="{% url 'posts:post_list' %}" class="btn btn-secondary">Powrót</a>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "main.html" %}

{% load bootstrap4 %}

{% block title %}Lista postów{% endblock %}

{% block content %}
<div class="row">

    <!-- Lewa kolumna: lista postów -->
    <div class="col-md-8">
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th>Tytuł</th>
                    <th>Autor</th>
                    <th>Data</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td>
                            <a href="{% url 'posts:post_detail' post.pk %}">
                                {{ post.title }}
                            </a>
                        </td>
                        <td>{{ post.author.nick }}</td>
                        <td>{{ post.created|date:"F j, Y, g:i a" }}</td>
                    </tr>
                {% empty %}
                    <tr><td colspan="3"><em>Brak postów</em></td></tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Paginacja -->
        {% if posts.has_other_pages %}
            <nav>
                <ul class="pagination justify-content-center">
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
                        </li>
                    {% endif %}
                    {% for num in posts.paginator.page_range %}
                        <li class="page-item {% if posts.number == num %}active{% endif %}">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endfor %}
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>

    <!-- Prawa kolumna: formularz dodawania -->
    <div class="col-md-4">
        {% if perms.posts.add_post %}
        <h4 class="mb-3">Dodaj nowy</h4>
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            {% bootstrap_form form  %}
            <input type="submit" value="Dodaj">
        </form>
        {% else %}
        {% endif %}
    </div>
</div>
{% endblock %}